
export const shippingRates = [
  { "origen": "BOGOTA D.C.", "destino": "ACACIAS", "departamento": "META", "tipo_trayecto": "NACIONAL", "tarifa": 1760.0 },
  { "origen": "BOGOTA D.C.", "destino": "AGUACHICA", "departamento": "CESAR", "tipo_trayecto": "NACIONAL", "tarifa": 2506.9 },
  { "origen": "BOGOTA D.C.", "destino": "AGUAZUL", "departamento": "CASANARE", "tipo_trayecto": "NACIONAL", "tarifa": 2255 },
  { "origen": "BOGOTA D.C.", "destino": "AIPE", "departamento": "HUILA", "tipo_trayecto": "NACIONAL", "tarifa": 1523.5 },
  { "origen": "BOGOTA D.C.", "destino": "ALTAMIRA (HUI)", "departamento": "HUILA", "tipo_trayecto": "NACIONAL", "tarifa": 2675.2 },
  { "origen": "BOGOTA D.C.", "destino": "ALVARADO", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 2035.0 },
  { "origen": "BOGOTA D.C.", "destino": "ANAPOIMA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1958.0 },
  { "origen": "BOGOTA D.C.", "destino": "ANSERMANUEVO", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 2255 },
  { "origen": "BOGOTA D.C.", "destino": "APULO", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1980.0 },
  { "origen": "BOGOTA D.C.", "destino": "ARACATACA", "departamento": "MAGDALENA", "tipo_trayecto": "NACIONAL", "tarifa": 2332 },
  { "origen": "BOGOTA D.C.", "destino": "ARJONA (BOL)", "departamento": "BOLIVAR", "tipo_trayecto": "NACIONAL", "tarifa": 1980.0 },
  { "origen": "BOGOTA D.C.", "destino": "ARMENIA (QUI)", "departamento": "QUINDIO", "tipo_trayecto": "NACIONAL", "tarifa": 1100 },
  { "origen": "BOGOTA D.C.", "destino": "ARMERO GUAYABAL", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 2035.0 },
  { "origen": "BOGOTA D.C.", "destino": "BARANOA", "departamento": "ATLANTICO", "tipo_trayecto": "NACIONAL", "tarifa": 2200 },
  { "origen": "BOGOTA D.C.", "destino": "BARBOSA (ANT)", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1265 },
  { "origen": "BOGOTA D.C.", "destino": "BARBOSA (SNR)", "departamento": "SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 2042.7 },
  { "origen": "BOGOTA D.C.", "destino": "BARRANCABERMEJA", "departamento": "SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 1870.0 },
  { "origen": "BOGOTA D.C.", "destino": "BARRANQUILLA", "departamento": "ATLANTICO", "tipo_trayecto": "NACIONAL", "tarifa": 1584.0 },
  { "origen": "BOGOTA D.C.", "destino": "BELALCAZAR (CAL)", "departamento": "CALDAS", "tipo_trayecto": "NACIONAL", "tarifa": 2640 },
  { "origen": "BOGOTA D.C.", "destino": "BELLO", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "BOGOTA D.C.", "departamento": "CUNDINAMARCA", "tipo_trayecto": "URBANO", "tarifa": 544.5 },
  { "origen": "BOGOTA D.C.", "destino": "BOJACA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1045 },
  { "origen": "BOGOTA D.C.", "destino": "BUCARAMANGA", "departamento": "SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "BUENAVENTURA", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 2420 },
  { "origen": "BOGOTA D.C.", "destino": "BUGALAGRANDE", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1628.0 },
  { "origen": "BOGOTA D.C.", "destino": "CAICEDONIA", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 2200 },
  { "origen": "BOGOTA D.C.", "destino": "CAIMITO", "departamento": "SUCRE", "tipo_trayecto": "NACIONAL", "tarifa": 2640 },
  { "origen": "BOGOTA D.C.", "destino": "CAJAMARCA", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1683.0 },
  { "origen": "BOGOTA D.C.", "destino": "CAJICA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "URBANO", "tarifa": 544.5 },
  { "origen": "BOGOTA D.C.", "destino": "CALARCA", "departamento": "QUINDIO", "tipo_trayecto": "NACIONAL", "tarifa": 1100 },
  { "origen": "BOGOTA D.C.", "destino": "CALDAS (ANT)", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "CALI", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "CALOTO", "departamento": "CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1650.0 },
  { "origen": "BOGOTA D.C.", "destino": "CAMPOALEGRE (HUI)", "departamento": "HUILA", "tipo_trayecto": "NACIONAL", "tarifa": 1936.0 },
  { "origen": "BOGOTA D.C.", "destino": "CANDELARIA (VAL)", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "CAQUEZA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 2530 },
  { "origen": "BOGOTA D.C.", "destino": "CARTAGENA DE INDIAS", "departamento": "BOLIVAR", "tipo_trayecto": "NACIONAL", "tarifa": 1705.0 },
  { "origen": "BOGOTA D.C.", "destino": "CARTAGO", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "CAUCASIA", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 2519 },
  { "origen": "BOGOTA D.C.", "destino": "CERETE", "departamento": "CORDOBA", "tipo_trayecto": "NACIONAL", "tarifa": 2475 },
  { "origen": "BOGOTA D.C.", "destino": "CHAPARRAL", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1958.0 },
  { "origen": "BOGOTA D.C.", "destino": "CHIA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "URBANO", "tarifa": 544.5 },
  { "origen": "BOGOTA D.C.", "destino": "CHINCHINA", "departamento": "CALDAS", "tipo_trayecto": "NACIONAL", "tarifa": 1478.4 },
  { "origen": "BOGOTA D.C.", "destino": "CHINU", "departamento": "CORDOBA", "tipo_trayecto": "NACIONAL", "tarifa": 2530 },
  { "origen": "BOGOTA D.C.", "destino": "CHIPAQUE", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 2530 },
  { "origen": "BOGOTA D.C.", "destino": "CHIQUINQUIRA", "departamento": "BOYACA", "tipo_trayecto": "NACIONAL", "tarifa": 1162.7 },
  { "origen": "BOGOTA D.C.", "destino": "CHOCONTA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1155 },
  { "origen": "BOGOTA D.C.", "destino": "CIENAGA", "departamento": "MAGDALENA", "tipo_trayecto": "NACIONAL", "tarifa": 2403.5 },
  { "origen": "BOGOTA D.C.", "destino": "CIRCASIA", "departamento": "QUINDIO", "tipo_trayecto": "NACIONAL", "tarifa": 1191.3 },
  { "origen": "BOGOTA D.C.", "destino": "COGUA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 880.0 },
  { "origen": "BOGOTA D.C.", "destino": "COMBITA", "departamento": "BOYACA", "tipo_trayecto": "NACIONAL", "tarifa": 1520.2 },
  { "origen": "BOGOTA D.C.", "destino": "COPACABANA", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "COTA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "URBANO", "tarifa": 544.5 },
  { "origen": "BOGOTA D.C.", "destino": "CUCUTA", "departamento": "NORTE DE SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 1870.0 },
  { "origen": "BOGOTA D.C.", "destino": "DAGUA", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 2431 },
  { "origen": "BOGOTA D.C.", "destino": "DOSQUEBRADAS", "departamento": "RISARALDA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "DUITAMA", "departamento": "BOYACA", "tipo_trayecto": "NACIONAL", "tarifa": 1067 },
  { "origen": "BOGOTA D.C.", "destino": "EL CARMEN DE VIBORAL", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1158.3 },
  { "origen": "BOGOTA D.C.", "destino": "EL CERRITO", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "EL PLAYON", "departamento": "SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 2222 },
  { "origen": "BOGOTA D.C.", "destino": "EL RETIRO", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1265 },
  { "origen": "BOGOTA D.C.", "destino": "EL ROSAL", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 772.2 },
  { "origen": "BOGOTA D.C.", "destino": "EL SANTUARIO", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1265 },
  { "origen": "BOGOTA D.C.", "destino": "EL ZULIA", "departamento": "NORTE DE SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 2035.0 },
  { "origen": "BOGOTA D.C.", "destino": "ENVIGADO", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "ESPINAL", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1210 },
  { "origen": "BOGOTA D.C.", "destino": "FACATATIVA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "URBANO", "tarifa": 544.5 },
  { "origen": "BOGOTA D.C.", "destino": "FLANDES", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1067 },
  { "origen": "BOGOTA D.C.", "destino": "FLORENCIA (CAQ)", "departamento": "CAQUETA", "tipo_trayecto": "NACIONAL", "tarifa": 2420 },
  { "origen": "BOGOTA D.C.", "destino": "FLORIDA", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1760.0 },
  { "origen": "BOGOTA D.C.", "destino": "FLORIDABLANCA", "departamento": "SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "FRESNO", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1628.0 },
  { "origen": "BOGOTA D.C.", "destino": "FUNDACION", "departamento": "MAGDALENA", "tipo_trayecto": "NACIONAL", "tarifa": 1925.0 },
  { "origen": "BOGOTA D.C.", "destino": "FUNZA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "URBANO", "tarifa": 544.5 },
  { "origen": "BOGOTA D.C.", "destino": "FUSAGASUGA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1067 },
  { "origen": "BOGOTA D.C.", "destino": "GACHANCIPA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1067 },
  { "origen": "BOGOTA D.C.", "destino": "GALAPA", "departamento": "ATLANTICO", "tipo_trayecto": "NACIONAL", "tarifa": 1584.0 },
  { "origen": "BOGOTA D.C.", "destino": "GARZON", "departamento": "HUILA", "tipo_trayecto": "NACIONAL", "tarifa": 2035.0 },
  { "origen": "BOGOTA D.C.", "destino": "GIGANTE", "departamento": "HUILA", "tipo_trayecto": "NACIONAL", "tarifa": 2035.0 },
  { "origen": "BOGOTA D.C.", "destino": "GINEBRA", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1936.0 },
  { "origen": "BOGOTA D.C.", "destino": "GIRARDOT", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1122 },
  { "origen": "BOGOTA D.C.", "destino": "GIRARDOTA", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "GIRON", "departamento": "SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "GUACARI", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1936.0 },
  { "origen": "BOGOTA D.C.", "destino": "GUADALAJARA DE BUGA", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1980.0 },
  { "origen": "BOGOTA D.C.", "destino": "GUADUAS", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1375 },
  { "origen": "BOGOTA D.C.", "destino": "GUAMO", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1760.0 },
  { "origen": "BOGOTA D.C.", "destino": "GUARNE", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1100 },
  { "origen": "BOGOTA D.C.", "destino": "GUAYABETAL", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 2126.3 },
  { "origen": "BOGOTA D.C.", "destino": "HOBO", "departamento": "HUILA", "tipo_trayecto": "NACIONAL", "tarifa": 1804.0 },
  { "origen": "BOGOTA D.C.", "destino": "HONDA", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1320 },
  { "origen": "BOGOTA D.C.", "destino": "IBAGUE", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "IPIALES", "departamento": "NARIÑO", "tipo_trayecto": "NACIONAL", "tarifa": 2296.8 },
  { "origen": "BOGOTA D.C.", "destino": "ITAGUI", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "JAMUNDI", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "JUAN DE ACOSTA", "departamento": "ATLANTICO", "tipo_trayecto": "NACIONAL", "tarifa": 2640 },
  { "origen": "BOGOTA D.C.", "destino": "LA CALERA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 660 },
  { "origen": "BOGOTA D.C.", "destino": "LA CEJA", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1265 },
  { "origen": "BOGOTA D.C.", "destino": "LA DORADA (CAL)", "departamento": "CALDAS", "tipo_trayecto": "NACIONAL", "tarifa": 1617.0 },
  { "origen": "BOGOTA D.C.", "destino": "LA ESTRELLA", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "LA MESA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1870.0 },
  { "origen": "BOGOTA D.C.", "destino": "LA PAILA", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 2167 },
  { "origen": "BOGOTA D.C.", "destino": "LA TEBAIDA", "departamento": "QUINDIO", "tipo_trayecto": "NACIONAL", "tarifa": 1650.0 },
  { "origen": "BOGOTA D.C.", "destino": "LA UNION (VAL)", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 2090 },
  { "origen": "BOGOTA D.C.", "destino": "LA VEGA (CUN)", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1265 },
  { "origen": "BOGOTA D.C.", "destino": "LA VICTORIA (VAL)", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 2090 },
  { "origen": "BOGOTA D.C.", "destino": "LA VIRGINIA", "departamento": "RISARALDA", "tipo_trayecto": "NACIONAL", "tarifa": 1628.0 },
  { "origen": "BOGOTA D.C.", "destino": "LEBRIJA", "departamento": "SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 1371.7 },
  { "origen": "BOGOTA D.C.", "destino": "LERIDA", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1870.0 },
  { "origen": "BOGOTA D.C.", "destino": "LOS PALMITOS", "departamento": "SUCRE", "tipo_trayecto": "NACIONAL", "tarifa": 2530 },
  { "origen": "BOGOTA D.C.", "destino": "LOS PATIOS", "departamento": "NORTE DE SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 1842.5 },
  { "origen": "BOGOTA D.C.", "destino": "LURUACO", "departamento": "ATLANTICO", "tipo_trayecto": "NACIONAL", "tarifa": 2640 },
  { "origen": "BOGOTA D.C.", "destino": "MADRID", "departamento": "CUNDINAMARCA", "tipo_trayecto": "URBANO", "tarifa": 544.5 },
  { "origen": "BOGOTA D.C.", "destino": "MALAMBO", "departamento": "ATLANTICO", "tipo_trayecto": "NACIONAL", "tarifa": 1584.0 },
  { "origen": "BOGOTA D.C.", "destino": "MANIZALES", "departamento": "CALDAS", "tipo_trayecto": "NACIONAL", "tarifa": 1100 },
  { "origen": "BOGOTA D.C.", "destino": "MARIA LA BAJA", "departamento": "BOLIVAR", "tipo_trayecto": "NACIONAL", "tarifa": 2640 },
  { "origen": "BOGOTA D.C.", "destino": "MARINILLA", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1100 },
  { "origen": "BOGOTA D.C.", "destino": "MEDELLIN", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "MELGAR", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1188 },
  { "origen": "BOGOTA D.C.", "destino": "MONIQUIRA", "departamento": "BOYACA", "tipo_trayecto": "NACIONAL", "tarifa": 1765.5 },
  { "origen": "BOGOTA D.C.", "destino": "MONTENEGRO", "departamento": "QUINDIO", "tipo_trayecto": "NACIONAL", "tarifa": 1191.3 },
  { "origen": "BOGOTA D.C.", "destino": "MONTERIA", "departamento": "CORDOBA", "tipo_trayecto": "NACIONAL", "tarifa": 2475 },
  { "origen": "BOGOTA D.C.", "destino": "MORROA", "departamento": "SUCRE", "tipo_trayecto": "NACIONAL", "tarifa": 2475 },
  { "origen": "BOGOTA D.C.", "destino": "MOSQUERA (CUN)", "departamento": "CUNDINAMARCA", "tipo_trayecto": "URBANO", "tarifa": 544.5 },
  { "origen": "BOGOTA D.C.", "destino": "NATAGAIMA", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 2264.9 },
  { "origen": "BOGOTA D.C.", "destino": "NEIVA", "departamento": "HUILA", "tipo_trayecto": "NACIONAL", "tarifa": 1089 },
  { "origen": "BOGOTA D.C.", "destino": "NEMOCON", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1188 },
  { "origen": "BOGOTA D.C.", "destino": "NILO", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 2026.2 },
  { "origen": "BOGOTA D.C.", "destino": "NOBSA", "departamento": "BOYACA", "tipo_trayecto": "NACIONAL", "tarifa": 1375 },
  { "origen": "BOGOTA D.C.", "destino": "OBANDO", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1870.0 },
  { "origen": "BOGOTA D.C.", "destino": "OCAÑA", "departamento": "NORTE DE SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 2098.8 },
  { "origen": "BOGOTA D.C.", "destino": "OIBA", "departamento": "SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 2587.2 },
  { "origen": "BOGOTA D.C.", "destino": "ORTEGA", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1925.0 },
  { "origen": "BOGOTA D.C.", "destino": "PAIPA", "departamento": "BOYACA", "tipo_trayecto": "NACIONAL", "tarifa": 1177 },
  { "origen": "BOGOTA D.C.", "destino": "PALMIRA", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "PALOCABILDO", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 2750 },
  { "origen": "BOGOTA D.C.", "destino": "PEREIRA", "departamento": "RISARALDA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "PIEDECUESTA", "departamento": "SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "PITALITO", "departamento": "HUILA", "tipo_trayecto": "NACIONAL", "tarifa": 1980.0 },
  { "origen": "BOGOTA D.C.", "destino": "PLANETA RICA", "departamento": "CORDOBA", "tipo_trayecto": "NACIONAL", "tarifa": 2368.3 },
  { "origen": "BOGOTA D.C.", "destino": "PONEDERA", "departamento": "ATLANTICO", "tipo_trayecto": "NACIONAL", "tarifa": 2695 },
  { "origen": "BOGOTA D.C.", "destino": "POPAYAN", "departamento": "CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1870.0 },
  { "origen": "BOGOTA D.C.", "destino": "PRADERA", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1936.0 },
  { "origen": "BOGOTA D.C.", "destino": "PRADO", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1870.0 },
  { "origen": "BOGOTA D.C.", "destino": "PUEBLO NUEVO (COR)", "departamento": "CORDOBA", "tipo_trayecto": "NACIONAL", "tarifa": 2475 },
  { "origen": "BOGOTA D.C.", "destino": "PUENTE NACIONAL", "departamento": "SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 2222 },
  { "origen": "BOGOTA D.C.", "destino": "PUERTO BOYACA", "departamento": "BOYACA", "tipo_trayecto": "NACIONAL", "tarifa": 1980.0 },
  { "origen": "BOGOTA D.C.", "destino": "PUERTO COLOMBIA (ATL)", "departamento": "ATLANTICO", "tipo_trayecto": "NACIONAL", "tarifa": 1606.0 },
  { "origen": "BOGOTA D.C.", "destino": "PUERTO SALGAR", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1760.0 },
  { "origen": "BOGOTA D.C.", "destino": "PUERTO TEJADA", "departamento": "CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1430.0 },
  { "origen": "BOGOTA D.C.", "destino": "PURIFICACION", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1870.0 },
  { "origen": "BOGOTA D.C.", "destino": "QUETAME", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 2090 },
  { "origen": "BOGOTA D.C.", "destino": "QUIMBAYA", "departamento": "QUINDIO", "tipo_trayecto": "NACIONAL", "tarifa": 1191.3 },
  { "origen": "BOGOTA D.C.", "destino": "REPELON", "departamento": "ATLANTICO", "tipo_trayecto": "NACIONAL", "tarifa": 2552 },
  { "origen": "BOGOTA D.C.", "destino": "RICAURTE (CUN)", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1122 },
  { "origen": "BOGOTA D.C.", "destino": "RIONEGRO (ANT)", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1100 },
  { "origen": "BOGOTA D.C.", "destino": "RIONEGRO (SNR)", "departamento": "SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 1760.0 },
  { "origen": "BOGOTA D.C.", "destino": "ROLDANILLO", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 2035.0 },
  { "origen": "BOGOTA D.C.", "destino": "ROVIRA", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1980.0 },
  { "origen": "BOGOTA D.C.", "destino": "SABANAGRANDE", "departamento": "ATLANTICO", "tipo_trayecto": "NACIONAL", "tarifa": 2200 },
  { "origen": "BOGOTA D.C.", "destino": "SABANALARGA (ATL)", "departamento": "ATLANTICO", "tipo_trayecto": "NACIONAL", "tarifa": 2145 },
  { "origen": "BOGOTA D.C.", "destino": "SABANETA", "departamento": "ANTIOQUIA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "SAHAGUN", "departamento": "CORDOBA", "tipo_trayecto": "NACIONAL", "tarifa": 2530 },
  { "origen": "BOGOTA D.C.", "destino": "SALDAÑA", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1980.0 },
  { "origen": "BOGOTA D.C.", "destino": "SAN ALBERTO", "departamento": "CESAR", "tipo_trayecto": "NACIONAL", "tarifa": 2297.9 },
  { "origen": "BOGOTA D.C.", "destino": "SAN GIL", "departamento": "SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 1870.0 },
  { "origen": "BOGOTA D.C.", "destino": "SAN JUAN DE PASTO", "departamento": "NARIÑO", "tipo_trayecto": "NACIONAL", "tarifa": 1903.0 },
  { "origen": "BOGOTA D.C.", "destino": "SAN MARTIN (MET)", "departamento": "META", "tipo_trayecto": "NACIONAL", "tarifa": 1650.0 },
  { "origen": "BOGOTA D.C.", "destino": "SAN PEDRO (VAL)", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 2200 },
  { "origen": "BOGOTA D.C.", "destino": "SAN SEBASTIAN DE MARIQUITA", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1628.0 },
  { "origen": "BOGOTA D.C.", "destino": "SANTA CRUZ DE LORICA", "departamento": "CORDOBA", "tipo_trayecto": "NACIONAL", "tarifa": 2530 },
  { "origen": "BOGOTA D.C.", "destino": "SANTA MARTA", "departamento": "MAGDALENA", "tipo_trayecto": "NACIONAL", "tarifa": 2398 },
  { "origen": "BOGOTA D.C.", "destino": "SANTA ROSA DE CABAL", "departamento": "RISARALDA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "SANTANDER DE QUILICHAO", "departamento": "CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1705.0 },
  { "origen": "BOGOTA D.C.", "destino": "SANTO TOMAS", "departamento": "ATLANTICO", "tipo_trayecto": "NACIONAL", "tarifa": 2310 },
  { "origen": "BOGOTA D.C.", "destino": "SASAIMA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1650.0 },
  { "origen": "BOGOTA D.C.", "destino": "SEVILLA (VAL)", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 2035.0 },
  { "origen": "BOGOTA D.C.", "destino": "SIBATE", "departamento": "CUNDINAMARCA", "tipo_trayecto": "URBANO", "tarifa": 544.5 },
  { "origen": "BOGOTA D.C.", "destino": "SIBERIA (CUN)", "departamento": "CUNDINAMARCA", "tipo_trayecto": "URBANO", "tarifa": 544.5 },
  { "origen": "BOGOTA D.C.", "destino": "SILVANIA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1210 },
  { "origen": "BOGOTA D.C.", "destino": "SINCE", "departamento": "SUCRE", "tipo_trayecto": "NACIONAL", "tarifa": 2640 },
  { "origen": "BOGOTA D.C.", "destino": "SINCELEJO", "departamento": "SUCRE", "tipo_trayecto": "NACIONAL", "tarifa": 2310 },
  { "origen": "BOGOTA D.C.", "destino": "SOACHA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "URBANO", "tarifa": 544.5 },
  { "origen": "BOGOTA D.C.", "destino": "SOCORRO", "departamento": "SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 1877.7 },
  { "origen": "BOGOTA D.C.", "destino": "SOGAMOSO", "departamento": "BOYACA", "tipo_trayecto": "NACIONAL", "tarifa": 1100 },
  { "origen": "BOGOTA D.C.", "destino": "SOLEDAD", "departamento": "ATLANTICO", "tipo_trayecto": "NACIONAL", "tarifa": 1584.0 },
  { "origen": "BOGOTA D.C.", "destino": "SOPO", "departamento": "CUNDINAMARCA", "tipo_trayecto": "URBANO", "tarifa": 533.5 },
  { "origen": "BOGOTA D.C.", "destino": "SORACA", "departamento": "BOYACA", "tipo_trayecto": "NACIONAL", "tarifa": 1709.4 },
  { "origen": "BOGOTA D.C.", "destino": "SUBACHOQUE", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 990.0 },
  { "origen": "BOGOTA D.C.", "destino": "TABIO", "departamento": "CUNDINAMARCA", "tipo_trayecto": "URBANO", "tarifa": 544.5 },
  { "origen": "BOGOTA D.C.", "destino": "TENJO", "departamento": "CUNDINAMARCA", "tipo_trayecto": "URBANO", "tarifa": 544.5 },
  { "origen": "BOGOTA D.C.", "destino": "TIBASOSA", "departamento": "BOYACA", "tipo_trayecto": "NACIONAL", "tarifa": 1309 },
  { "origen": "BOGOTA D.C.", "destino": "TOCAIMA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1808.4 },
  { "origen": "BOGOTA D.C.", "destino": "TOCANCIPA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "URBANO", "tarifa": 544.5 },
  { "origen": "BOGOTA D.C.", "destino": "TOLU", "departamento": "SUCRE", "tipo_trayecto": "NACIONAL", "tarifa": 2640 },
  { "origen": "BOGOTA D.C.", "destino": "TORO", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 2156 },
  { "origen": "BOGOTA D.C.", "destino": "TULUA", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1925.0 },
  { "origen": "BOGOTA D.C.", "destino": "TUNJA", "departamento": "BOYACA", "tipo_trayecto": "NACIONAL", "tarifa": 1023.0 },
  { "origen": "BOGOTA D.C.", "destino": "TURBACO", "departamento": "BOLIVAR", "tipo_trayecto": "NACIONAL", "tarifa": 1705.0 },
  { "origen": "BOGOTA D.C.", "destino": "VALLEDUPAR", "departamento": "CESAR", "tipo_trayecto": "NACIONAL", "tarifa": 2750 },
  { "origen": "BOGOTA D.C.", "destino": "VENADILLO", "departamento": "TOLIMA", "tipo_trayecto": "NACIONAL", "tarifa": 1870.0 },
  { "origen": "BOGOTA D.C.", "destino": "VENTAQUEMADA", "departamento": "BOYACA", "tipo_trayecto": "NACIONAL", "tarifa": 2090 },
  { "origen": "BOGOTA D.C.", "destino": "VIJES", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 2420 },
  { "origen": "BOGOTA D.C.", "destino": "VILLA DE LEYVA", "departamento": "BOYACA", "tipo_trayecto": "NACIONAL", "tarifa": 1320 },
  { "origen": "BOGOTA D.C.", "destino": "VILLA DE SAN DIEGO DE UBATE", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1188 },
  { "origen": "BOGOTA D.C.", "destino": "VILLA DEL ROSARIO", "departamento": "NORTE DE SANTANDER", "tipo_trayecto": "NACIONAL", "tarifa": 1813.9 },
  { "origen": "BOGOTA D.C.", "destino": "VILLA RICA", "departamento": "CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1628.0 },
  { "origen": "BOGOTA D.C.", "destino": "VILLAMARIA", "departamento": "CALDAS", "tipo_trayecto": "NACIONAL", "tarifa": 1100 },
  { "origen": "BOGOTA D.C.", "destino": "VILLAPINZON", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1430.0 },
  { "origen": "BOGOTA D.C.", "destino": "VILLAVICENCIO", "departamento": "META", "tipo_trayecto": "NACIONAL", "tarifa": 1045 },
  { "origen": "BOGOTA D.C.", "destino": "VILLETA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 1320 },
  { "origen": "BOGOTA D.C.", "destino": "YOPAL", "departamento": "CASANARE", "tipo_trayecto": "NACIONAL", "tarifa": 1870.0 },
  { "origen": "BOGOTA D.C.", "destino": "YOTOCO", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 2255 },
  { "origen": "BOGOTA D.C.", "destino": "YUMBO", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 1026.3 },
  { "origen": "BOGOTA D.C.", "destino": "ZARZAL", "departamento": "VALLE DEL CAUCA", "tipo_trayecto": "NACIONAL", "tarifa": 2035.0 },
  { "origen": "BOGOTA D.C.", "destino": "ZIPAQUIRA", "departamento": "CUNDINAMARCA", "tipo_trayecto": "NACIONAL", "tarifa": 638 }
];

export const cityOptions = [...new Set(shippingRates.map(rate => rate.destino))].sort().map(city => ({
    value: city,
    label: city,
}));
